FROM node:latest

ENV PATH ./app/node_modules/.bin:$PATH

RUN mkdir -p /home/app

COPY ./app /home/app

# set default dir so that next commands executes in /home/app dir
WORKDIR /home/app

# will execute npm install in /home/app because of WORKDIR
RUN npm install --silent

# no need for /home/app/server.js because of WORKDIR
CMD ["npm", "start"]
